# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: raguillo <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/13 20:16:13 by raguillo          #+#    #+#              #
#    Updated: 2018/11/14 10:51:10 by raguillo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file.c

EXE = ft_display_file

OBJCT = ft_display_file.o

all:
	gcc -Wall -Wextra -Werror -o $(EXE) $(NAME)

clean:
	rm -f $(OBJCT)

fclean: clean
	rm -f $(EXE)
